import os
import requests
try:
    from crewai import Agent, Task, Crew, Process
except ImportError:
    # Fallback implementations if the 'crewai' package isn't available.
    class Agent:
        def __init__(self, role, goal, backstory=None, verbose=False, allow_delegation=True):
            self.role = role
            self.goal = goal
            self.backstory = backstory
            self.verbose = verbose
            self.allow_delegation = allow_delegation

    class Task:
        def __init__(self, description, expected_output=None, agent=None):
            self.description = description
            self.expected_output = expected_output
            self.agent = agent

    class Process:
        Parallel = 'parallel'
        Sequential = 'sequential'

    class Crew:
        def __init__(self, agents=None, tasks=None, process=None):
            self.agents = agents or []
            self.tasks = tasks or []
            self.process = process

        def run(self):
            # Simple simulated run: return each task and which agent would perform it.
            results = []
            for t in self.tasks:
                performer = getattr(t.agent, 'role', 'unknown')
                results.append({'task': t.description, 'performed_by': performer})
            return {'status': 'fallback', 'results': results}

# --- Configuration ---
TARGET_ENDPOINT = "http://100.71.195.41:20128/v1"

def run_api_interaction_crew():
    """
    Initializes and runs a crew to interact with the specified external API endpoint.
    """
    print("--- Starting CrewAI Workflow for API Interaction ---")

    # 1. Define Agents
    # Agent responsible for understanding the goal and structuring the API call.
    researcher = Agent(
        role='API Integration Specialist',
        goal=f'Analyze the requirements and interact with the external API at {TARGET_ENDPOINT} to achieve the main objective.',
        backstory="A senior developer expert in REST APIs and workflow automation.",
        verbose=True,
        allow_delegation=False
    )

    # Agent responsible for executing the actual HTTP requests.
    executor = Agent(
        role='API Executor',
        goal='Execute precise HTTP requests (GET, POST, etc.) to the target endpoint using provided parameters.',
        backstory="A reliable system that only executes code when explicitly instructed.",
        verbose=True,
        allow_delegation=False
    )

    # 2. Define Tasks
    # Task for the Researcher to plan the interaction.
    task_plan = Task(
        description=f'Determine the necessary steps and payload structure required to interact with {TARGET_ENDPOINT}. Outline a clear sequence of API calls.',
        expected_output='A detailed, step-by-step plan including endpoints, methods (GET/POST), and required JSON payloads.',
        agent=researcher
    )

    # Task for the Executor to perform the actual call based on the plan.
    task_execute = Task(
        description=f'Execute the API calls as per the plan generated by the Researcher. Use the requests library to interact with {TARGET_ENDPOINT}.',
        expected_output='The raw JSON response from the successful API interaction, or a detailed error message.',
        agent=executor
    )

    # 3. Run the Crew
    try:
        crew = Crew(
            agents=[researcher, executor],
            tasks=[task_plan, task_execute],
            process=Process.Parallel
        )
        result = crew.run()
        print(f"Result: {result}")
    except Exception as e:
        print(f"Error running crew: {e}")
        # Fallback: Direct API interaction if crew fails
        print("Attempting direct API interaction as fallback...")
        try:
            response = requests.get(TARGET_ENDPOINT, timeout=10)
            response.raise_for_status()
            print(f"Direct API response: {response.json()}")
        except requests.exceptions.RequestException as req_error:
            print(f"Direct API interaction failed: {req_error}")

if __name__ == "__main__":
    run_api_interaction_crew()